vich_uploader:
  db_driver: orm

  mappings:
    employee:
      uri_prefix: /images/employee
      upload_destination: "%kernel.project_dir%/public/images/employee"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
