vich_uploader:
  db_driver: orm

  mappings:
    employees:
      uri_prefix: /images/employees
      upload_destination: "%kernel.project_dir%/public/images/employees"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
