version: "3.8"

services:
  php:
    container_name: php_backofice
    build:
      context: ./docker/php-fpm
    ports:
      - "9002:9000"
    volumes:
      - ./:/var/www/back_office:cached
    depends_on:
      - database
  nginx:
    container_name: nginx_backoffice
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony_docker:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  ###> doctrine/doctrine-bundle ###
  database:
    container_name: database_backoffice
    image: mysql:8.0
    environment:
      # You should definitely change the password in production
    MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
    MYSQL_USER: root
    volumes:
      - database_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
